services:
  mysql:
    image: mysql:8.0
    container_name: mysql-task7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: computer_store
    volumes:
      - ./src/work1/task7/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/work1/task7/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    command: --default-authentication-plugin=mysql_native_password